### ISSUE TITLE
Three Layer System for objects.

### ISSUE THREAD

**Issue by Aubron** [fabricjs/api-discussion#6]
## The problem to solve
* When attempting to add in more advanced features on top of fabric's stock featureset (A goal preferred to adding advanced editor functionality to the core fabric product), object layering frequently becomes an issue.
* Overlays are currently limited to images and `fabric.Pattern`s.
* Overlays and backgrounds have kind of odd APIs whose names don't reflect their capabilities (canvas.setOverlayColor takes a pattern, for example)

## Current situation
1. I would like to render a control object above my fabric objects. I don't want to have to worry about shuffling objects around to make sure it is always on top. My control is neither an image or a color/pattern (all that is supported via `overlay`), so I have difficulty writing it.

2. I would like to render a control _under_ my fabric objects. The same issues apply, and the only consistent recourse is canvas.setBackgroundColor/setBackgroundImage

3. Some of these issues can be solved via `after:render`, but not all. `after:render` paints over fabric's stock controls and doesn't give you the object caching properties of fabric.

## Proposal

Convert the current fabric system, which contains a single array of objects, a single background, and a single overlay, into a three array system.

Instead of just `canvas.getObjects()`, there would be `canvas.getBackgroundObjects()` and `canvas.getOverlayObjects()` as well, as well as functions to add, reorder, and remove objects from those arrays.

There would be more powerful options available to those who want to write their own canvas based controls (literally) on top of fabric, and we could simplify some mild confusion in the API. If the arrays are empty, we could simply not render them, making it not a huge performance hit.

## Breaking changes

1. `canvas.setOverlayColor/Image` and `canvas.setBackgroundColor/Image` would enter a deprecation cycle. This would probably be a big break for a lot of applications, and we might want to maintain utility functions `canvas.setBackground() and canvas.setOverlay()` to facilitate the learning curve and migration of existing applications.
2. Examples would need to be updated.

**Comment by asturur** [comment]
Well this could be solved with a before:render and after:render PER OBJECT.
This would allow you to intervene before a specific object paint and after a specific object paint.

Is also true that most of the people do editors with fabricJS, and would want to have this for the active object and not turning it on and of for each objects.

For the object caching, here there is some issue since you have to know how big are those things you want to draw, without knowing it cache can't be really done.

i agree the overlay and background( color / image ) are weird named:

the colors take any fillable: colorString, gradient, pattern
the image take any Fabric.Object derivate ( groups included )

**Comment by Aubron** [comment]
Yes, realistically if we had
```
before:render for canvas
after:render for canvas that triggers before controls were drawn
after:(controls?) for canvas that triggers after controls are drawn
before:render for object
after:render for object
```

This would allow reasonably smart code for most the things I want to do. Especially if I could hook into the object context in the object render events.

**Comment by asturur** [comment]
yes the per object events should get the object context, but that would require to do not touch the context ( canvas ) size since that would kill whatever has been drawn there before.

Those would be really advanced/delicate events in which you have to know what are you doing.

also those events would fire just on cache invalidation, or each render for uncached use case.

I have headache just thinking of all combinations of errors a dev could do.

**Comment by Aubron** [comment]
Is there a case for just saying 'if you want custom after render functionality for an object you should subclass'?

**Comment by asturur** [comment]
No.
The problem you encounter would be the same, it would just rise the bar of complexity for people to implement it.

A dev that writes:

```javascript
render(ctx) {
  this.callSuper('render', ctx);
  this.fire('object:after:render', { ctx: ctx });
  // OR myrender(ctx);
}
```

Does not solve any problem, the only realy difference is that with the custom event you get an array per object in the emitter area that contains a reference to your after:render event, with the subclass not. Compared with all memory usage of resources taken by fabricJS i tend to not consider it at all, and i prefer something that is easier to use.

I would separate this issue from the event one, and change its title to `custom render events` or something like that.
